version: '3.8'

services:
  app:
    image: node:20
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ecommerce-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  minio:
    image: minio/minio
    container_name: minio-client
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./minio_data:/data
    command: minio server /data --console-address ":9090"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
